// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_option from "rescript/lib/es6/js_option.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function rafLoop(draw, fps) {
  var delay = Caml_int32.div(1000, fps);
  var tmp = {
    contents: 0
  };
  var raf_handle = {
    contents: undefined
  };
  var last = {
    contents: 0
  };
  var frame = {
    contents: -1
  };
  var pause = function (param) {
    var rafId = raf_handle.contents;
    if (rafId !== undefined) {
      cancelAnimationFrame(Caml_option.valFromOption(rafId));
      last.contents = 0;
      raf_handle.contents = undefined;
      frame.contents = -1;
      return ;
    }
    
  };
  var loop = function (time) {
    if (last.contents === 0) {
      last.contents = time;
    }
    tmp.contents = Caml_int32.div(time - last.contents | 0, delay);
    if (Js_option.isSome(raf_handle.contents)) {
      if (tmp.contents > frame.contents) {
        frame.contents = tmp.contents;
        draw(frame.contents, pause);
      }
      raf_handle.contents = Caml_option.some(requestAnimationFrame(loop));
      return ;
    }
    
  };
  var play = function (param) {
    if (Js_option.isNone(raf_handle.contents)) {
      raf_handle.contents = Caml_option.some(requestAnimationFrame(loop));
      return ;
    }
    
  };
  return {
          play: play,
          pause: pause
        };
}

export {
  rafLoop ,
  
}
/* No side effect */
